{{ if $.Values.global.extraConfigurationSecrets }}
{{ range $secretname, $filePath := $.Values.global.extraConfigurationSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretname }}
type: Opaque
data:
{{ ( $.Files.Glob ( printf "%s%s" "configfiles" $filePath ) ).AsSecrets | indent 2 }}
---
{{ end }}
{{ end }}
