{{ range $applicationname, $application := merge .Values.applications .Values.jobs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $applicationname }}-conf-secret
type: Opaque
data:
{{ if $application.alternativeConfigFiles }}
{{ ( printf "#%s%s%s" "configfiles" $application.workdir $application.alternativeConfigFiles ) }}
{{ ( $.Files.Glob ( printf "%s%s%s" "configfiles" $application.workdir $application.alternativeConfigFiles ) ).AsSecrets | indent 2 }}
{{ else }}
{{ ( printf "#%s%s%s" "configfiles" $application.workdir "/cfg/*" ) }}
{{ ( $.Files.Glob ( printf "%s%s%s" "configfiles" $application.workdir "/cfg/*" ) ).AsSecrets | indent 2 }}
{{ end }}

---
{{ end }}
