apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-global-conf-secret
type: Opaque
data:
{{ ( $.Files.Glob ( printf "%s%s%s" "configfiles" $.Values.global.defaultConfLocation "/*" ) ).AsSecrets | indent 2 }}