apiVersion: v2
name: custom-helm
version: 1.0.0
appVersion: 1.0.0
description: Custom Helm Chart
keywords:
- kubernetes
maintainers:
- email: mail@jasper.bremenkamp.de
  name: jasper
  url: https://jasper.bremenkamp.de
dependencies:
  - name: kafka
    version: "30.1.6"
    repository: "oci://registry-1.docker.io/bitnamicharts"